redis:
    build: ./redis
    ports:
      - "6378:6379"
    restart: always
logstashindexerkds:
    build: ./logstash
    volumes:
        - ~/opt-kds-watcher/htdocs/Dockerfiles/logstash/kds/index.conf:/opt/logstash/conf/index.conf
    links:
        - "redis"
    command: logstash agent  -f /opt/logstash/conf/index.conf
    restart: always
logstashagentkds:
    build: ./logstash
    volumes:
        - ~/opt-kds-watcher/htdocs/Dockerfiles/logstash/kds/agent.conf:/opt/logstash/conf/agent.conf
    links:
        - "redis"
    command: logstash agent  -f /opt/logstash/conf/agent.conf
    restart: always
